routes/web.php
<?php

use App\Http\Controllers\VoitureController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('voitures',VoitureController::class);

app/Models/Marque.php
<?php

namespace App\Models;

use App\Models\Voiture;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Marque extends Model
{
    use HasFactory;
    protected $fillable=['nom','description'];

    public function voitures(){
        return $this->hasMany(Voiture::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Models/Voiture.php
<?php

namespace App\Models;

use App\Models\Marque;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Voiture extends Model
{
    use HasFactory;
    protected $fillable=['immatriculation','nbrChevaux','description','marque_id'];

    public function marque(){
        return $this->belongsTo(Marque::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/VoitureController.php
<?php

namespace App\Http\Controllers;

use App\Models\Marque;
use App\Models\Voiture;
use Illuminate\Http\Request;

class VoitureController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $voitures=Voiture::paginate(20);
        return view("voitures.index",compact('voitures'));

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $marques=Marque::select('id','nom')->get();
        return view('voitures.create',compact('marques'));

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $validated_data=$request->validate([
            "immatriculation"=>'required',
            "nbrChevaux"=>'required',
            "description"=>"required",
            "marque_id"=>"required",
            'image'=>'image|mimes:jpeg,png,jpg,gif,svg,webp|max:80000',
        ]);
        if($request->hasFile('image')){
            $imagePath=$request->file('image')->store('products/images','public');
            $validated_data['image']=$imagePath;
        }
        Voiture::create($validated_data);
        return redirect()->route('voitures.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
        $voiture=Voiture::find($id);
        return view("voitures.show",compact('voiture'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
        $voiture=Voiture::find($id);
        $marques=Marque::select('id','nom')->get();
        return view('voitures.edit',compact('voiture','marques'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
        $validated_data=$request->validate([
            "immatriculation"=>'required',
            "nbrChevaux"=>'required',
            "description"=>"required",
            "marque_id"=>"required"
        ]);
        $voiture=Voiture::find($id);
        $voiture->update($validated_data);
        return redirect()->route('voitures.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
        $voiture=Voiture::find($id);
        $voiture->delete();
        return redirect()->route('voitures.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <a href="{{route('voitures.index')}}">Gestion voitures</a>
            <a href="#">Gestion marques</a>
        </nav>
    </header>
    <div id="container">
        @yield('content')
    </div>
    <footer>
        name website
    </footer>
</body>
</html>

resources/views/voitures/index.blade.php
@extends('layouts.app')
@section('content')
<a href="{{route('voitures.create')}}" id="ajouter">Ajouter une voiture</a>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Immatriculation</th>
            <th>Nombre chevaux</th>
            <th>Description</th>
            <th>Marque</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($voitures as $item)
            <tr>
                <td>{{$item->id}}</td>
                <td>{{$item->immatriculation}}</td>
                <td>{{$item->nbrChevaux}}</td>
                <td>{{$item->description}}</td>
                <td>{{$item->marque->nom}}</td>
                <td> <img src="{{asset('storage/'.$item->image)}}" alt="#"> </td>
                <td>
                    <a href="{{route('voitures.show',$item->id)}}">Detail</a>
                    <a href="{{route('voitures.edit',$item->id)}}">Editer</a>
                    <form action="{{route('voitures.destroy',$item->id)}}" method="post">
                        @method('delete')
                        @csrf
                        <input type="submit" value="Supprimer">
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
    
@endsection